repos:
- repo: https://github.com/igorshubovych/markdownlint-cli
  # https://github.com/igorshubovych/markdownlint-cli/issues/540
  rev: v0.45.0
  hooks:
  - id: markdownlint
    args:
    - --fix
    # https://github.com/DavidAnson/markdownlint/blob/main/doc/md059.md
    # for > 0.45.0
    # - "--disable=MD059"

# Does it work on m1?
#- repo: https://github.com/gitleaks/gitleaks
#  rev: v8.18.2
#  hooks:
#    - id: gitleaks
