site_name: Open Data Manager Documentation
site_url: https://genestack.github.io/documentation

nav:
    - Home: index.md
    - User guide:
          - Packages to install:
                - Genestack python client: user-guide/packages-to-install/genestack-python-client.md
                - Genestack auxiliary scripts: user-guide/packages-to-install/genestack-auxiliary-scripts.md
          - Users:
                - Users creation: user-guide/users/user-creation.md
          - Templates:
                - Create or update template: user-guide/templates/create-or-update-template.md
                - Delete template: user-guide/templates/delete-template.md
          - Working with study:
                - Uploading study: user-guide/working-with-study/uploading-study.md
                - Curation script: user-guide/working-with-study/curation-script.md
                - Sharing study: user-guide/working-with-study/sharing-study.md
                - Deleting study: user-guide/working-with-study/deleting-study.md
                - Loading from GEO: user-guide/working-with-study/loading-from-geo.md
          - Dictionaries and ontologies:
                - Default dictionaries: user-guide/dictionaries-and-ontologies/default-dictionaries.md
                - Exporting ontologies from ODM: user-guide/dictionaries-and-ontologies/exporting-ontologies-from-odm.md
                - Creating new dictionary: user-guide/dictionaries-and-ontologies/creating-new-dictionary.md
                - Loading new ontology:
                      - user-guide/dictionaries-and-ontologies/loading-new-ontology.md
                      - CSV dictionary format: user-guide/dictionaries-and-ontologies/loading-new-ontology/csv-dictionary-format.md
          - Data Retrieving: user-guide/data-retrieving.md
          - Training Materials: user-guide/training-materials.md
    - Release notes: release-notes.md

theme:
    name: material
    palette:
        primary: custom
        accent: custom
    logo: assets/logo.svg
    favicon: assets/favicon.ico
    features:
        - announce.dismiss
        - content.action.edit
        - content.action.view
        - content.code.annotate
        - content.code.copy
        # - content.code.select
        # - content.tabs.link
        - content.tooltips
        # - header.autohide
        # - navigation.expand
        - navigation.footer
        - navigation.indexes
        # - navigation.instant
        # - navigation.instant.prefetch
        # - navigation.instant.progress
        # - navigation.prune
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        # - toc.integrate
extra:
    version:
        provider: mike
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - md_in_html
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.tabbed:
          alternate_style: true
    - tables
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true
    - codehilite
    - pymdownx.tabbed
    - toc:
          permalink: true
