site_name: Open Data Manager Documentation
site_url: https://genestack.github.io/documentation

nav:
    - Home: index.md
    - Deployment:
        - Requirements:
            - Kubernetes: deployment/requirements/kubernetes.md
            - Hardware: deployment/requirements/hardware.md
            - External services: deployment/requirements/external-services.md
        - Clouds:
            - Amazon Web Services (AWS): deployment/clouds/aws.md
            - Microsoft Azure: deployment/clouds/azure.md
        - Single Sign-On:
            - About SSO in ODM: deployment/single-sign-on/sso.md
            - OpenID:
                - Microsoft Azure: deployment/single-sign-on/openid/azure.md
                - Google Workspace: deployment/single-sign-on/openid/google.md
                - Okta: deployment/single-sign-on/openid/okta.md
            - SAML:
                - Google Workspace: deployment/single-sign-on/saml/google.md
                - Okta: deployment/single-sign-on/saml/okta.md
            - SCIM:
                - Microsoft Azure: deployment/single-sign-on/scim/azure.md
        - Helm:
            - How to deploy: deployment/helm/how-to-deploy.md
        - Troubleshooting:
            - AWS S3: deployment/troubleshooting/aws-s3.md
            - Azure SSO: deployment/troubleshooting/azure-sso.md
            - Azure SCIM: deployment/troubleshooting/azure-scim.md
        - Release Notes:
              - v1.50 - v1.59: deployment/release-notes/v1.50-v1.59.md
    - Release notes:
          - v1.50 - v1.59: release-notes/v1.50-v1.59.md
          - v1.40 - v1.49: release-notes/v1.40-v1.49.md
          - v1.30 - v1.39: release-notes/v1.30-v1.39.md
          - v1.20 - v1.29: release-notes/v1.20-v1.29.md
theme:
    name: material
    palette:
        primary: custom
        accent: custom
    logo: assets/logo.svg
    favicon: assets/favicon.ico
    features:
        - announce.dismiss
        - content.action.edit
        - content.action.view
        - content.code.annotate
        - content.code.copy
        # - content.code.select
        # - content.tabs.link
        - content.tooltips
        # - header.autohide
        # - navigation.expand
        - navigation.footer
        - navigation.indexes
        # - navigation.instant
        # - navigation.instant.prefetch
        # - navigation.instant.progress
        # - navigation.prune
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        # - toc.integrate
extra:
    version:
        provider: mike
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - md_in_html
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.tabbed:
          alternate_style: true
    - tables
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - codehilite
    - pymdownx.tabbed
    - toc:
        permalink: true
